int appWidth, appHeight;
float GlobeCubeX, GlobeCubeY, GlobeCubeWidth, GlobeCubeHeight;
float centerX, centerY;
float CircleX, CircleY, CircleDiameter;
float DuckX, DuckY, DuckD, Duck2X, Duck2Y, Duck2D; 
float topX, topY, topExtent;
Boolean landscape=false, portrait=false;
float PacmanX, PacmanY, PacmanWidth, PacmanHeight;
float waterX, waterY, waterD;
color WaterColour, Yellow=#FFE80F, resetWhite=#FFFFFF; 
int waterR;
int reset=1;
boolean nightMode=false, REd=false, ORange=false, YEllow=false, GReen=false, BLue=false, VIolet=false, WHite=false, GRey=false, PInk=false;
